name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:  
    runs-on: ubuntu-latest
    
    env:      
      DOCKER_REGISTRY: registry.hub.docker.com
      DOCKER_IMAGE: rhernaus/rpi-pulsecounter      
      DOCKER_TARGET_PLATFORM: linux/arm/v7          
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Buildx
      if: success()      
      run: |        
        docker buildx build \
        --platform ${DOCKER_TARGET_PLATFORM} \
        --tag ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:$(date +%s) \
        --tag ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest \
        --file ./Dockerfile \
        --output type=image,push=true .
