name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:  
    runs-on: ubuntu-latest
    
    env:      
      DOCKER_REGISTRY: registry.hub.docker.com
      DOCKER_IMAGE: rhernaus/rpi-pulsecounter
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      DOCKER_TARGET_PLATFORM: linux/arm/v7          
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login      
      if: success()      
      run: |        
        echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin 
    - name: Buildx
      if: success()      
      run: |        
        docker buildx build \
        --platform ${DOCKER_TARGET_PLATFORM} \
        --tag ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:$(date +%s) \
        --file ./Dockerfile \
        --output type=image,push=true .
